---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    my_bucket_name: orlando-ansible-bucket

  tasks:
  - name: Create EC2 instance
    ec2:
      key_name: Orlando
      instance_type: t2.micro
      image: ami-8a7859ef
      wait: yes
      count: 1
      vpc_subnet_id: subnet-4a6ef131
      region: us-east-2
      instance_tags:
        Name: orlando-ansible

  - ec2_instance_facts:
    filters:
      "tag:Name": orlando-ansible
