---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    my_tag_name: orlando-ansible

  tasks:
  - ec2_instance_facts:
    filters:
      "tag:Name": orlando-ansible
    register: my_list

  - debug:
      msg: "Instances: {{ my_list['instances']['root_device_type'] }}"
