---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: us-east-2
    instance_ids:
      - 'i-0b2ff55e7dd974f2c'
      - 'i-08e0543792a141426'

  tasks:
  - name: Terminate instance 
    ec2:
      instance_ids: '{{ instance_ids }}'
      state: 'absent'
      region: '{{ region }}'
