- hosts: localhost
  vars:
    my_bucket_name: orlando-new-bucket

  tasks:
  - name: List buckets
    aws_s3_bucket_facts:
    register: s3_buckets
  
  - debug:
      msg: "Buckets: {{ s3_buckets }}"

  - name: Create an empty bucket
    aws_s3:
      bucket: "{{ my_bucket_name }}"
      mode: create
      permission: private

  - name: Upload files
    aws_s3:
      bucket: "{{ my_bucket_name }}"
      object: uploads/sample2.txt
      src: uploads/sample2.txt
      mode: put

  - name: Sync directory
    s3_sync:
      bucket: '{{ my_bucket_name }}'
      file_root: uploads/
      key_prefix: uploads
