---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    my_bucket_name: orlando-ansible-bucket

  tasks:
  - name: List buckets
    aws_s3_bucket_facts:
    register: s3_buckets
  
  - debug:
      msg: "Buckets: {{ s3_buckets }}"

  - name: Create an empty bucket
    aws_s3:
      bucket: "{{ my_bucket_name }}"
      mode: create
      permission: private

  - name: Upload files
    aws_s3:
      bucket: "{{ my_bucket_name }}"
      object: uploads/sample2.txt
      src: uploads/sample2.txt
      overwrite: different
      mode: put

  - name: Sync uploads directory
    s3_sync:
      bucket: '{{ my_bucket_name }}'
      file_root: uploads/
      key_prefix: uploads
      file_change_strategy: date_size
      include: "*.txt"
      delete: True

  - name: Sync Downloads directory
    s3_sync:
      bucket: '{{ my_bucket_name }}'
      file_root: uploads/
      key_prefix: downloads
      file_change_strategy: date_size
      include: "*.jpg"